heatmap_type: scaled_zero_zone
model_name: squeezenet1_1
dataset_name: cifar10
save_path: results
num_images: 1000
no_pretrained: false
adapt_model: false
occlusion_patch_size: 1
max_level: 4
knn_k: 10
knn_num_pixels: 100
knn_patch_size: 5
npy_input_dir: null
